### ISSUE TITLE
Update command line guidance

### ISSUE THREAD

**Issue by larsvilhuber** [labordynamicsinstitute/replicability-training#7]
Move to Markdown

Augment to encompass Windows and Bash versions.

**Comment by dwasser** [comment]
Pull request sent to merge new markdown document. But this still needs info for best ways to access command line from Windows vs Mac etc

**Comment by larsvilhuber** [comment]
@dwasser  Need to actually move it to Markdown - we were using the PDF? Also "touch" does not work in powershell
